###########################################
#
#  ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
#  ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#     ██║   ██╔████╔██║██║   ██║ ╚███╔╝ 
#     ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗ 
#     ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#     ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#  Dr.MuteSTEVE tmux config!
#
###########################################
set -g history-limit 10000
set -g mouse on
set -g base-index 1
set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g automatic-rename on

# Tmux statusbar
wg_prfx=" #{?client_prefix,<Prefix>,}"
wg_time=" | %H:%M:%S"
wg_date=" | %A-%d-%b-%Y |"
wg_session=" #{session_name} "
wg_name=" #(echo Session:)"
set -g status-interval 1
set -g status-left-length 50
set -g status-right-length 50
set -g status-right "${wg_prfx}${wg_time}${wg_date}"
set -g status-left "${wg_name}${wg_session}"

# Tmux statusbar color
set -g status-position top
set -g status-style bg=#1E1E1E,fg=#ffffff
set -g window-status-current-style bg=#03395E,fg=#ffffff

#  ██  ██  
# ████████ 
#  ██  ██  
# ████████ 
#  ██  ██  
# Keybind
# bind = prefix/ctrl+a + {key}
# bind -n = without using prefix/ctrl+a
# M- = alt
# C- = ctrl
# S- = shift

# changing prefix/ctrl+b to prefix/ctrl+a who would want to type "b" that's far from ctrl key eh?
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# (r)eload config
bind r source-file ~/.config/tmux/tmux.conf\; display "Tmux config has been reloaded!"

# Switch between split pane
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Switch window index with alt+number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-c new-window

# Spawn split pane vertical and horizontal
bind -n M-v split-window -v
bind -n M-h split-window -h

# Resize pane
bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5
bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5

# Move windows index to left or right 
bind -n C-S-Left swap-window -t -1
bind -n C-S-Right swap-window -t +1
