###########################################
#
#  ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
#  ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#     ██║   ██╔████╔██║██║   ██║ ╚███╔╝ 
#     ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗ 
#     ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#     ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#  Dr.MuteSTEVE tmux config!
#
###########################################
set -ag terminal-overrides ",xterm-256color:RGB"
set -g automatic-rename on
set -g base-index 1
set -g default-terminal "tmux-256color"
set -g history-limit 10000
set -g mouse on
set -sg escape-time 0

#  ██  ██  
# ████████ 
#  ██  ██  
# ████████ 
#  ██  ██  
# Keybind
# bind = prefix/ctrl+a + {key}
# bind -n = without using prefix/ctrl+a
# M- = alt
# C- = ctrl
# S- = shift
prfx=C-a
alt=M
ctrl=C

# changing prefix/ctrl+b to prefix/ctrl+a who would want to type "b" that's far from ctrl key eh?
unbind C-b
set -g prefix $prfx
bind $prfx send-prefix

# (r)eload config
bind r source-file ~/.config/tmux/tmux.conf\; display "Tmux config has been reloaded!"

# Switch between split pane
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Switch window index with alt+number
bind -n $alt-1 select-window -t 1
bind -n $alt-2 select-window -t 2
bind -n $alt-3 select-window -t 3
bind -n $alt-4 select-window -t 4
bind -n $alt-5 select-window -t 5
bind -n $alt-6 select-window -t 6
bind -n $alt-7 select-window -t 7
bind -n $alt-8 select-window -t 8
bind -n $alt-9 select-window -t 9
bind -n $alt-c new-window

# Spawn split pane vertical and horizontal
bind -n $alt-v split-window -v
bind -n $alt-h split-window -h

# Resize pane
bind -n ctrl-Left resize-pane -L 5
bind -n ctrl-Right resize-pane -R 5
bind -n ctrl-Up resize-pane -U 5
bind -n ctrl-Down resize-pane -D 5

# Move windows index to left or right 
bind -n ctrl-S-Left swap-window -t -1
bind -n ctrl-S-Right swap-window -t +1

#  ██  ██  
# ████████ 
#  ██  ██  
# ████████ 
#  ██  ██  
# Tmux statusbar
status_bg=#1E1E1E
status_fg=#ffffff
window_bg=#03395E
split_bg=#007ACC

# Tmux statusbar color
set -g status-position top
set -g status-style bg=$status_bg,fg=$status_fg

# status-left
wg_name=" #(echo Session:)"
wg_session=" #{session_name} | "
set -g status-left "${wg_name}${wg_session}"

# status-right
wg_prfx=" #{?client_prefix,<$prfx> ,}"
wg_time=" %H:%M:%S"
wg_date=" | %A-%d-%b-%Y"
wg_position=" | #{?pane_at_top,,} "
set -g status-right "${wg_prfx}${wg_time}${wg_date}${wg_position}"

# window-index
set -g window-status-format "#{window_index}#(echo :)#{window_name} "
set -g window-status-current-style bg=$window_bg,fg=$status_fg

# Statusbar settings
set -g status-interval 1
set -g status-left-length 50
set -g status-right-length 50
set -g pane-active-border-style bg=default,fg=$status_bg
set -g pane-border-style fg=$status_bg
