set $foreground rgb({foreground.strip})
set $background rgb({background.strip})

set $color0 rgb({color0.strip})
set $color1 rgb({color1.strip})
set $color2 rgb({color2.strip})
set $color3 rgb({color3.strip})
set $color4 rgb({color4.strip})
set $color5 rgb({color5.strip})
set $color6 rgb({color6.strip})
set $color7 rgb({color7.strip})
set $color8 rgb({color8.strip})
set $color9 rgb({color9.strip})
set $color10 rgb({color10.strip})
set $color11 rgb({color11.strip})
set $color12 rgb({color12.strip})
set $color13 rgb({color13.strip})
set $color14 rgb({color14.strip})
set $color15 rgb({color15.strip}) 
