#!/bin/bash

# Import function from src/aptInstall 
source ./aptInstall
source ./configs

packages_pulseaudio=(
    "pulseaudio"
    "pavucontrol"
)

packages_pipewire=(
    "pavucontrol"
    "pipewire"
    "pipewire-alsa"
    "wireplumber"
)

case $AUDIO in
    "pulseaudio") packages="packages_pulseaudio" ;;
    "pipewire") packages="packages_pipewire" ;;
esac

aptInstall "${packages[@]}"
