#!/usr/bin/env bash

list=(
    ".bashrc"
    ".bash_profile"
    ".gitconfig"
    ".inputrc"
    ".config/"
    ".local/"
)
username_template=(
    "$HOME/.config/kitty/kitty.conf"
)

for copy in "${list[@]}"; do
    cp -r "$PWD/${copy}" $HOME/
done
chmod +x $HOME/.local/bin/*

for username in "${username_template[@]}"; do
    sed -i "s|USERNAME_HERE|$USER|" "$username"
done
