#!/bin/bash

# Import function from src/aptInstall 
source ./aptInstall
source ./configs

apt_fonts=(
    "fonts-noto-cjk-extra" 
    "fonts-noto-color-emoji" 
    "fonts-font-awesome"
)

nerd_fonts=( 
    "Hack"  
    "JetBrainsMono" 
    "LiberationMono" 
)

# Install using imported function  from src/aptInstall
aptInstall "${apt_fonts[@]}"

mkdir -p $FONT_DIR
for font in ${nerd_fonts[@]}
do
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v$FONT_VERSION/$font.tar.xz
	tar -xvf $font.tar.xz -C "$FONT_DIR/$font/"
    rm -fr $font.tar.xz
done
fc-cache -fv
