#!/bin/bash

# Import function from src/aptInstall 
source ./aptInstall
source ./configs

packages=(
    "fcitx5"
    "fcitx5-config-qt"
    "fcitx5-data"
    "fcitx5-frontend-gtk2"
    "fcitx5-frontend-gtk3"
    "fcitx5-frontend-gtk4"
    "fcitx5-frontend-qt5"
    "fcitx5-frontend-qt6"
    "fcitx5-modules"
    "fcitx5-modules-dev"
    "fcitx5-mozc"
    "ffmpeg"
    "mpv"
)

# Install using imported function  from src/aptInstall
aptInstall "${packages[@]}"

# Manual install anki
wget https://github.com/ankitects/anki/releases/download/$ANKI_VERSION/anki-launcher-$ANKI_VERSION-linux.tar.zst
tar -xvf anki-launcher-$ANKI_VERSION-linux.tar.zst
cd anki-launcher-$ANKI_VERSION-linux/
chmod +x install.sh
./install.sh
rm -fr anki-launcher-$ANKI_VERSION-linux/
