#!/usr/bin/env bash

## Import function from src/InstallFunc
source ./InstallFunc

list_pacman=(
    "fcitx5"
    "fcitx5-configtool"
    "fcitx5-mozc"
    "fcitx5-gtk"
    "fcitx5-qt"
    "ffmpeg"
    "mpv"
)

local list_yay=(
    "anki-bin"
)

## Install using imported function  from src/InstallFunc
operation_with -p "${list_pacman[@]}"
operation_with -y "${list_yay[@]}"

local mpv_DIR=$HOME/.config/mpv/scripts/
if [[ ! -d "$mpv_DIR" ]] || [[ -z "$(ls -A "$mpv_DIR")" ]]; then
    mkdir -p "$mpv_DIR"
    git clone 'https://github.com/Ajatt-Tools/mpvacious.git' "${mpv_DIR}/subs2srs"
fi
