#!/usr/bin/env bash

## Import function and configuration from src/
source src/InstallFunc
source src/configs

list_pacman=(
    "kitty"
    "nitrogen"
    "sxhkd"
    "xclip"
    "xorg"
    "xorg-xinit"
)

list_yay=(
    "python-pywal16"
    $BROWSER
)

## Artix linux does have xlibre, which is replacement of xorg
if [[ $DISTRO == "artix" ]]; then
    new_list=()
    for value in "${list_pacman[@]}"; do
        [[ $value == "xorg" ]] && continue  ## I hate 3 level deep nesting
        new_list+=("$value")
    done
    list_pacman=("${new_list[@]}")
    unset new_list
fi

## Install using imported function  from src/InstallFunc
operation_with -p "${list_pacman[@]}"
operation_with -y "${list_yay[@]}"
