#!/bin/bash

# Import function from src/aptInstall 
source ./aptInstall
source ./configs

packages=(
    "brightnessctl"
    "cliphist"
    "grim"
    "kitty"
    "pavucontrol"
    "pipewire"
    "slurp"
    "sway-notification-center"
    "waybar"
    "wget"
    "wl-clipboard"
    "xdg-user-dirs"
    "xdg-utils"
)

# Install using imported function  from src/aptInstall
aptInstall "${packages[@]}"

git clone "https://github.com/hyprwm/Hyprland"
cd Hyprland
make all && sudo make install
cd -
rm -fr Hyprland
